<a href="https://colab.research.google.com/github/saddarudin/google_colab/blob/main/dl_word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

In [5]:
reviews = [
    'nice food',
    'amazing restaurant',
    'too good',
    'just loved it!',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
]
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer

vocab_size = 30
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(reviews)


encoded_reviews = tokenizer.texts_to_sequences(reviews)
print("Integer sequences:", encoded_reviews)

Integer sequences: [[5, 2], [6, 7], [8, 9], [10, 11, 12], [13, 3, 14], [15, 2], [16, 3, 17], [4, 18], [4, 19], [20, 21]]


In [15]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post', truncating='post')
print("Padded sequences:", padded_reviews)

Padded sequences: [[ 5  2  0]
 [ 6  7  0]
 [ 8  9  0]
 [10 11 12]
 [13  3 14]
 [15  2  0]
 [16  3 17]
 [ 4 18  0]
 [ 4 19  0]
 [20 21  0]]


In [16]:
embedded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
x = padded_reviews
y = sentiment

In [18]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.fit(x,y,epochs=50,verbose=0)

In [20]:
model.evaluate(x,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - accuracy: 1.0000 - loss: 0.6081


[0.6080523133277893, 1.0]

In [22]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

## In encoded reviews the number for food is 2 so in weights we will see the embedded vector at index 2 which is for food

In [23]:
weights[2]

array([-0.00828721,  0.02866727, -0.01789251, -0.03328687, -0.0438486 ],
      dtype=float32)