<a href="https://colab.research.google.com/github/saddarudin/google_colab/blob/main/nlp_word_vectors_in_gensim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy==1.24.3 scipy==1.10.1 gensim --force-reinstall --no-cache-dir

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.9/58.9 kB 122.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 209.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.1/34.1 MB 250.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 241.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 206.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.2/83.2 kB 243.2 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.2
    Uninstalling wrapt-1.17.2:
      Successfully uninstalled wrapt-1.17.2
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: smart-open
    Found existing installation: smart-open 7.1.0
    Uninstalling smart-open-7.1.0:
      Successfully uninstalled smart-open-7.1.0
  Attempting uninstall: scipy
    Found existing ins

## word2vec-google-news-300 is trained model by google

In [1]:
import gensim.downloader as api

# Load Google News Word2Vec model
wv = api.load("word2vec-google-news-300")


[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [2]:
wv.similarity(w1="great", w2="good")

0.72915095

In [3]:
wv.similarity(w1="profit", w2="loss")

0.34199455

In [4]:
wv.similarity(w1='apple',w2='banana')

0.5318406

In [5]:
wv.similarity(w1='apple',w2='iphone')

0.31990406

In [6]:
wv.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [7]:
wv.most_similar("Saddar")

[('Liaquatabad', 0.7322434782981873),
 ('Aabpara', 0.7225515842437744),
 ('Cantt', 0.7172930836677551),
 ('Kharadar', 0.7090997099876404),
 ('Gulberg', 0.70017009973526),
 ('Sadiqabad', 0.6993118524551392),
 ('Mozang', 0.6991147994995117),
 ('Quaidabad', 0.6986273527145386),
 ('Pirwadhai', 0.6941980719566345),
 ('Chowk', 0.6904984712600708)]

In [8]:
wv.most_similar("fuck")

[('fucking', 0.8137823343276978),
 ('f_*_ck', 0.801154613494873),
 ('f_**_k', 0.7815893888473511),
 ('shit', 0.7604621648788452),
 ('fucked', 0.7501130700111389),
 ('fuckin', 0.7309141755104065),
 ('f_***', 0.7172754406929016),
 ('f_ck', 0.7121477127075195),
 ('f_---', 0.7099311947822571),
 ('Fuck', 0.7066987156867981)]

## France - Paris + Berlin = Germany
### Actually Paris is capital of France and Berlin is Capital of Germany, France is country so it takes properties of country and by changing capital it considers that country matching capital

In [9]:
wv.most_similar(positive=['france','berlin'],negative=['paris'])

[('germany', 0.5094343423843384),
 ('european', 0.48650455474853516),
 ('german', 0.4714890420436859),
 ('austria', 0.46964022517204285),
 ('swedish', 0.4645182490348816),
 ('Wissenschaft', 0.4532880485057831),
 ('denmark', 0.4477355182170868),
 ('München', 0.4438532590866089),
 ('europe', 0.4420619308948517),
 ('belgium', 0.43769752979278564)]

### Similarly King-man+woman=Queen

In [10]:
wv.most_similar(positive=['king','woman'],negative=['man'])

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593831062317),
 ('monarchy', 0.5087411999702454)]

## Separating non-matching entities or tokens using "doesnt_match"

In [11]:
wv.doesnt_match(["facebook","cat","google","microsoft"])

'cat'

In [12]:
wv.doesnt_match(['Saddar', 'Azhar','Arshad','Zohaib','Saud','Pen'])

'Pen'

## Using another model glove-twitter-25

In [13]:
glv = api.load("glove-twitter-25")

[==================================================] 100.0% 104.8/104.8MB downloaded


In [14]:
glv.most_similar('good')

[('too', 0.9648017287254333),
 ('day', 0.9533665180206299),
 ('well', 0.9503170847892761),
 ('nice', 0.9438973665237427),
 ('better', 0.9425962567329407),
 ('fun', 0.9418926239013672),
 ('much', 0.9413353800773621),
 ('this', 0.9387555122375488),
 ('hope', 0.9383506774902344),
 ('great', 0.9378516674041748)]

In [15]:
wv.most_similar('good')

[('great', 0.7291510105133057),
 ('bad', 0.7190051078796387),
 ('terrific', 0.6889115571975708),
 ('decent', 0.6837348341941833),
 ('nice', 0.6836092472076416),
 ('excellent', 0.644292950630188),
 ('fantastic', 0.6407778263092041),
 ('better', 0.6120728850364685),
 ('solid', 0.5806034803390503),
 ('lousy', 0.576420247554779)]

In [16]:
glv.doesnt_match('breakfast cereal dinner lunch'.split())

'cereal'

In [17]:
glv.doesnt_match('banana apple grapes man'.split())

'man'

## Generating word vectors from google-news-300 model

In [18]:
wv_good = wv['good']
wv_good

array([ 0.04052734,  0.0625    , -0.01745605,  0.07861328,  0.03271484,
       -0.01263428,  0.00964355,  0.12353516, -0.02148438,  0.15234375,
       -0.05834961, -0.10644531,  0.02124023,  0.13574219, -0.13183594,
        0.17675781,  0.27148438,  0.13769531, -0.17382812, -0.14160156,
       -0.03076172,  0.19628906, -0.03295898,  0.125     ,  0.25390625,
        0.12695312, -0.15234375,  0.03198242,  0.01135254, -0.01361084,
       -0.12890625,  0.01019287,  0.23925781, -0.08447266,  0.140625  ,
        0.13085938, -0.04516602,  0.06494141,  0.02539062,  0.05615234,
        0.24609375, -0.20507812,  0.23632812, -0.00860596, -0.02294922,
        0.05078125,  0.10644531, -0.03564453,  0.08740234, -0.05712891,
        0.08496094,  0.23535156, -0.10107422, -0.03564453, -0.04736328,
        0.04736328, -0.14550781, -0.10986328,  0.14746094, -0.23242188,
       -0.07275391,  0.19628906, -0.37890625, -0.07226562,  0.04833984,
        0.11914062,  0.06103516, -0.12109375, -0.27929688,  0.05

## News Classification using Gensim

In [19]:
import pandas as pd

df = pd.read_csv('Fake_Real_Data.csv')
print(df.shape)
df.head()

(9900, 2)


Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [20]:
df.label.value_counts()

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9900 entries, 0 to 9899
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Text    9900 non-null   object
 1   label   9900 non-null   object
dtypes: object(2)
memory usage: 154.8+ KB


In [22]:
df['is_real'] = df.label.apply(lambda x: 1 if x=='Real' else 0)
df.head()

Text label  is_real
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake        0
1  U.S. conservative leader optimistic of common ...  Real        1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real        1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake        0
4  Democrats say Trump agrees to work on immigrat...  Real        1

In [23]:
!python -m spacy download en_core_web_lg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 5.3 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [24]:
import spacy

nlp = spacy.load('en_core_web_lg')

In [25]:
def preprocess_and_vectorize(text):
  doc = nlp(text)
  filtered_tokens = []

  for token in doc:
    if token.is_stop or token.is_punct:
      pass
    filtered_tokens.append(token.lemma_)

  return wv.get_mean_vector(filtered_tokens)

In [26]:
preprocess_and_vectorize('Hi, This is Saddar U Din Babar.')

array([-0.04807441,  0.05704265,  0.04416769,  0.05078912, -0.04073285,
        0.02337794,  0.00162314, -0.0356891 , -0.0096648 ,  0.02852952,
       -0.01952193, -0.03760855, -0.07192395,  0.00615138, -0.03495362,
        0.00873157,  0.02503311, -0.01245197,  0.00731879, -0.0131464 ,
       -0.02835541, -0.02702031,  0.03283944,  0.00305331,  0.00883616,
        0.02670032, -0.04255662, -0.0346972 ,  0.02567218, -0.01885219,
       -0.03612019, -0.00395071, -0.00533879,  0.00089125, -0.00108049,
        0.0001576 , -0.04669384, -0.00394088,  0.01498578, -0.00918492,
        0.03110231,  0.00373015,  0.07313249,  0.02225446,  0.01074037,
       -0.02413074,  0.00765042, -0.00571252, -0.00512609, -0.02332068,
        0.01569324,  0.03364996,  0.07464464,  0.04334353, -0.01538078,
       -0.00483283, -0.02757029,  0.00668747,  0.00466453, -0.04702218,
       -0.04128614,  0.01271287, -0.05131352,  0.00709279,  0.00467356,
       -0.03101601, -0.01727659,  0.05153232, -0.0040153 ,  0.06

In [27]:
df['vector'] = df.Text.apply(lambda x: preprocess_and_vectorize(x))
df.head()

Text label  is_real  \
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake        0   
1  U.S. conservative leader optimistic of common ...  Real        1   
2  Trump proposes U.S. tax overhaul, stirs concer...  Real        1   
3   Court Forces Ohio To Allow Millions Of Illega...  Fake        0   
4  Democrats say Trump agrees to work on immigrat...  Real        1   

                                              vector  
0  [0.01698693, 0.015109606, 0.008644394, 0.03866...  
1  [0.014535055, 0.009370668, 0.015304126, 0.0325...  
2  [0.019168077, 0.010601283, 0.011443579, 0.0451...  
3  [0.016010245, 0.015698142, 0.016139226, 0.0369...  
4  [0.0059666266, 0.013840894, 0.013304845, 0.039...

In [28]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    df.vector.values,
    df.is_real,
    test_size=0.2,
    random_state=2022,
    stratify=df.is_real
)

x_train.shape,x_test.shape

((7920,), (1980,))

## Reshaping x_train,x_test so that it fit the model

In [29]:
import numpy as np
x_train_2d = np.stack(x_train)
x_test_2d = np.stack(x_test)

x_train_2d.shape

(7920, 300)

In [30]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier()
model.fit(x_train_2d,y_train)

GradientBoostingClassifier()

In [31]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test_2d)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1000
           1       0.98      0.98      0.98       980

    accuracy                           0.98      1980
   macro avg       0.98      0.98      0.98      1980
weighted avg       0.98      0.98      0.98      1980



In [33]:
test_news = [
    "Top Trump Surrogate BRUTALLY Stabs Him In The Back: ‘He’s Pathetic’ (VIDEO) It s looking as though Republican presidential candidate Donald Trump is losing support even from within his own ranks. You know things are getting bad when even your top surrogates start turning against you, which is exactly what just happened on Fox News when Newt Gingrich called Trump  pathetic. Gingrich knows that Trump needs to keep his focus on Hillary Clinton if he even remotely wants to have a chance at defeating her. However, Trump has hurt feelings because many Republicans don t support his sexual assault against women have turned against him, including House Speaker Paul Ryan (R-WI). So, that has made Trump lash out as his own party.Gingrich said on Fox News: Look, first of all, let me just say about Trump, who I admire and I ve tried to help as much as I can. There s a big Trump and a little Trump. The little Trump is frankly pathetic. I mean, he s mad over not getting a phone call? Trump s referring to the fact that Paul Ryan didn t call to congratulate him after the debate. Probably because he didn t win despite what Trump s ego tells him.Gingrich also added: Donald Trump has one opponent. Her name is Hillary Clinton. Her name is not Paul Ryan. It s not anybody else. Trump doesn t seem to realize that the person he should be mad at is himself because he truly is his own worst enemy. This will ultimately lead to his defeat and he will have no one to blame but himself.Watch here via Politico:Featured Photo by Joe Raedle/Getty Images",
    "U.S. conservative leader optimistic of common ground on healthcare WASHINGTON (Reuters) - Republicans in the U.S. House of Representatives could achieve common ground on a deal to win support for healthcare legislation on Thursday, after President Donald Trump intervened in negotiations, a conservative leader said on Wednesday. “We’re not there yet, but we’re very optimistic that if we work around the clock between now and Noon tomorrow, that we’re going to be able to hopefully find some common ground,” Representative Mark Meadows, chairman of the conservative House Freedom Caucus, told reporters. Meadows’ group has opposed House Republican healthcare legislation up to now and threatened earlier in the day to block its passage in a Thursday vote.  ",
]

test_news_vectors = [preprocess_and_vectorize(x) for x in test_news]
test_news_vectors

[array([ 1.55771729e-02,  1.48208160e-02,  8.75554979e-03,  3.88537012e-02,
        -2.16624048e-02, -6.12980686e-03,  1.36091169e-02, -3.12341619e-02,
         3.92146856e-02,  2.13518571e-02, -1.91641748e-02, -4.86372337e-02,
        -1.60556473e-02,  2.02846806e-02, -4.64495234e-02,  2.87544411e-02,
         3.28804068e-02,  4.22661155e-02,  8.55800975e-03, -2.84695495e-02,
        -1.44321881e-02,  1.51828108e-02,  3.25185955e-02, -4.99808555e-03,
         1.89313311e-02, -1.69689720e-03, -3.82700861e-02,  1.18885813e-02,
         2.97176577e-02,  4.50452557e-03, -6.49056677e-03,  2.22248267e-02,
        -3.36397849e-02, -6.99117174e-03,  1.86030008e-02, -2.14943779e-03,
         2.15261094e-02,  5.09072607e-03,  8.59340653e-03,  2.47166865e-02,
         5.13196960e-02, -1.89393554e-02,  5.83368726e-02, -5.75553952e-03,
        -1.78637598e-02, -2.53277388e-03, -1.05339587e-02,  7.71770487e-03,
         1.63307581e-02,  2.57555656e-02, -1.53126405e-03,  3.58733796e-02,
        -9.5

In [34]:
model.predict(test_news_vectors)

array([0, 1])