### One Dimensional Array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [5]:
a.itemsize

8

In [9]:
a = np.array([2,4,6,8,10],dtype='int')

In [10]:
a

array([ 2,  4,  6,  8, 10])

In [11]:
a.itemsize

8

### Two Dimensional Array

In [12]:
a= np.array([[1,2,3],[3,4,5],[5,6,7]])
a.shape

(3, 3)

In [13]:
a[0].itemsize

8

In [14]:
a.itemsize

8

In [15]:
a[0][1] = 77
a

array([[ 1, 77,  3],
       [ 3,  4,  5],
       [ 5,  6,  7]])

### Zeros Function

In [16]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### ones function

In [17]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

### Array Range Function
### arange(a,b,c) where a=start, b=end,c=steps

In [18]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# odd numbers less than 20
arr = np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
print('Even numbers less than 21')
arr = np.arange(0,21,2)
arr

Even numbers less than 21


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Linearly Spaced numbers between two numbers

In [22]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [24]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

### Reshape Function

In [25]:
original_array = np.array([[1,2,3],[3,4,5]])
print(original_array)
print(original_array.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)


In [26]:
reshaped_array = original_array.reshape(3,2)
print(reshaped_array)
print(reshaped_array.shape)

[[1 2]
 [3 3]
 [4 5]]
(3, 2)


### Flattening Array using ravel function

### Ravel will not alter original array

In [27]:
flatten_array = reshaped_array.ravel()

In [28]:
flatten_array

array([1, 2, 3, 3, 4, 5])

In [29]:
reshaped_array

array([[1, 2],
       [3, 3],
       [4, 5]])

In [30]:
min(flatten_array)

np.int64(1)

In [31]:
flatten_array.min()

np.int64(1)

### Mathematical Functions on arrays

In [32]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])
print(a,b)

[[1 2]
 [3 4]] [[4 5]
 [6 7]]


In [33]:
a+b

array([[ 5,  7],
       [ 9, 11]])

In [35]:
a*b

array([[ 4, 10],
       [18, 28]])

In [36]:
a.dot(b)

array([[16, 19],
       [36, 43]])