## NumPy (Numerical Python) is the foundational package for numerical computations in Python.
## It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [1]:
import numpy as np

### Creating arrays

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
arr = np.array([[1,2,3],[3,4,5]])
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
arr = np.zeros((3,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.random.random((2,2))

array([[0.42251653, 0.78268455],
       [0.16635579, 0.54019046]])

In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace(a,b,c) it will generage c numbers in array from a to b which have same difference

In [10]:
np.linspace(2,10,3)

array([ 2.,  6., 10.])

## Array shape and reshaping

In [11]:
arr = np.array([[1,2,3],[2,3,4]])
arr.shape

(2, 3)

In [12]:
arr.reshape(3,2)

array([[1, 2],
       [3, 2],
       [3, 4]])

## Basic Array Operations

In [14]:
arr1 = np.arange(1,5)
arr2 = np.arange(6,10)
arr3 = arr1+arr2
arr3

array([ 7,  9, 11, 13])

In [15]:
arr1*arr2

array([ 6, 14, 24, 36])

In [16]:
arr1**2

array([ 1,  4,  9, 16])

In [17]:
np.sum(arr1)

10

In [18]:
np.mean(arr1)

2.5

In [19]:
np.min(arr2)

6

In [20]:
np.max(arr1)

4

### Array indexing and slicing

In [21]:
arr1[2]

3

In [22]:
arr1[1:3]

array([2, 3])

In [23]:
arr = np.array([[1,2,3],[3,4,5],[5,6,7]])
arr[1,1]

4

In [25]:
arr1

array([1, 2, 3, 4])

In [26]:
arr2

array([6, 7, 8, 9])

In [24]:
np.dot(arr1,arr2)

80

In [28]:
arr = np.array([[1,2,3],[2,3,4]])
arr

array([[1, 2, 3],
       [2, 3, 4]])

In [29]:
arr.T

array([[1, 2],
       [2, 3],
       [3, 4]])

## Handling Missing Values

In [31]:
arr = np.array([4,5,np.nan,6,7])
arr

array([ 4.,  5., nan,  6.,  7.])

In [32]:
np.isnan(arr)

array([False, False,  True, False, False])